version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./upload:/app/upload
    environment:
      - FRONTEND_URL=http://frontend:3000
      - UPLOAD_DIR=/app/upload
      - BASE_DIR=/app

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8000 